name: Continuos Integration

on: [push, pull_request]
  branches:
    [main]


jobs:
  continuos_integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: run install, build and test
        run: |
          go mod download
          go build -v
          go test -v