name: Continuos Integration

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  deploy:
    name: Continuos Integration
    runs-on: ubuntu-latest
    environment: gcp-prod
    env:
      IMG_NAME: "gcr.io/${{ secrets.GCP_PROJECT_ID }}/qrgen:latest"
    steps:
     #Git checkout
      - name: Checkout repository
        uses: actions/checkout@v2

    # Autenticação com Google Cloud
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # Setup gcloud
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

    #Congifure docker
      - name: Configure Docker
        run: gcloud auth configure-docker gcr.io --quiet

    #Build Image
      - name: Build Docker Image
        run: docker build -t $IMG_NAME .

    #Push Image
      - name: Push Docker Image
        run: docker push $IMG_NAME

    #Deploy Image
      - name: Deploy Docker Image
        run: gcloud run deploy qrgen --image $IMG_NAME --region us-central1 --memory 128Mi --min-instances 0 --max-instances 1 --platform managed --port 8080 --allow-unauthenticated
